# action.yml
name: 'Coverage Report'
author: 'Mark Wolfe <mark@wolfe.id.au>'
description: 'Generates a coverage report comment on Pull Requests'
branding:
  icon: 'message-square'  
  color: 'blue'
inputs:
  github-token:
    description: 'Github token for the repository'
    required: true
  coverage-report:
    description: 'path to coverage file'
    required: true
  minimum-coverage:
    description: 'Minimum allowed coverage.'
    required: true
  show-files:
    description: 'Show line rate for files.'
    required: true
    default: false
runs:
  using: docker
  image: docker://ghcr.io/wolfeidau/coverage-report-action:v1
  args:
  - '--coverage-report'
  - ${{ inputs.coverage-report }}
  - '--minimum-coverage'
  - ${{ inputs.minimum-coverage }}
