# action.yml
name: 'Coverage Report'
author: 'Mark Wolfe'
description: 'Generates a coverage report comment on Pull Requests'
inputs:
  github-token:
    description: 'Github token for the repository'
    required: true
  coverage-report:
    description: 'path to coverage file'
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
  - '--coverage-report'
  - ${{ inputs.coverage-report }}